[[tests]]
package = "efnet.utils"
object = "UartTx"
test = "test_uart_tx"
timescale = "1ns/100ps"
params = [
  {"width" = 8, "parity"= 1, "stop_bits" = 1},
  {"width" = 5, "parity"= 1, "stop_bits" = 1},
  {"width" = 5, "parity"= 1, "stop_bits" = 2},
  {"width" = 8, "parity"= 2, "stop_bits" = 1},
  {"width" = 8, "parity"= 0, "stop_bits" = 1},
]
disable = true

[[tests]]
package = "efnet.utils"
object = "ClockDivider"
test = "test_clock_divider"
params = [
  {"cnt" = 2 },
  # {"cnt" = 4 },
  # {"cnt" = 6 },
]
disable = true


[[tests]]
package = "efnet.utils"
object = "ParityGenerator"
test = "test_parity_generator"
params = [
  {"parity" = 0 },
  {"parity" = 1 },
  {"parity" = 2 },
]
disable = true

[[tests]]
package = "efnet.utils"
object = "UartRx"
test = "test_uart_rx"
timescale = "1ns/100ps"
params = [
  {"width" = 8, "parity"= 1, "stop_bits" = 1, "sample_freq" = 8}
]
# disable = true
