# ALLOWED_SIM_MODELS 
# ALLOWED_SIM_TYPES 
# BASE_BOARD_PART 
# BOARD 
# BOARD_CONNECTIONS 
# CAN_IP_GENERATE 
# CLASS 
# COMBINED_SIM_MODEL 
# CONFIG.AUTO_PRIMITIVE 
# CONFIG.AXI_DRP 
# CONFIG.CALC_DONE 
# CONFIG.CDDCDONE_PORT 
# CONFIG.CDDCREQ_PORT 
# CONFIG.CLKFB_IN_N_PORT 
# CONFIG.CLKFB_IN_PORT 
# CONFIG.CLKFB_IN_P_PORT 
# CONFIG.CLKFB_IN_SIGNALING 
# CONFIG.CLKFB_OUT_N_PORT 
# CONFIG.CLKFB_OUT_PORT 
# CONFIG.CLKFB_OUT_P_PORT 
# CONFIG.CLKFB_STOPPED_PORT 
# CONFIG.CLKIN1_JITTER_PS 
# CONFIG.CLKIN1_UI_JITTER 
# CONFIG.CLKIN2_JITTER_PS 
# CONFIG.CLKIN2_UI_JITTER 
# CONFIG.CLKOUT1_DRIVES 
# CONFIG.CLKOUT1_JITTER 
# CONFIG.CLKOUT1_MATCHED_ROUTING 
# CONFIG.CLKOUT1_PHASE_ERROR 
# CONFIG.CLKOUT1_REQUESTED_DUTY_CYCLE 
# CONFIG.CLKOUT1_REQUESTED_OUT_FREQ 
# CONFIG.CLKOUT1_REQUESTED_PHASE 
# CONFIG.CLKOUT1_SEQUENCE_NUMBER 
# CONFIG.CLKOUT1_USED 
# CONFIG.CLKOUT2_DRIVES 
# CONFIG.CLKOUT2_JITTER 
# CONFIG.CLKOUT2_MATCHED_ROUTING 
# CONFIG.CLKOUT2_PHASE_ERROR 
# CONFIG.CLKOUT2_REQUESTED_DUTY_CYCLE 
# CONFIG.CLKOUT2_REQUESTED_OUT_FREQ 
# CONFIG.CLKOUT2_REQUESTED_PHASE 
# CONFIG.CLKOUT2_SEQUENCE_NUMBER 
# CONFIG.CLKOUT2_USED 
# CONFIG.CLKOUT3_DRIVES 
# CONFIG.CLKOUT3_JITTER 
# CONFIG.CLKOUT3_MATCHED_ROUTING 
# CONFIG.CLKOUT3_PHASE_ERROR 
# CONFIG.CLKOUT3_REQUESTED_DUTY_CYCLE 
# CONFIG.CLKOUT3_REQUESTED_OUT_FREQ 
# CONFIG.CLKOUT3_REQUESTED_PHASE 
# CONFIG.CLKOUT3_SEQUENCE_NUMBER 
# CONFIG.CLKOUT3_USED 
# CONFIG.CLKOUT4_DRIVES 
#CONFIG.CLKOUT4_JITTER
#CONFIG.CLKOUT4_MATCHED_ROUTING
#CONFIG.CLKOUT4_PHASE_ERROR
#CONFIG.CLKOUT4_REQUESTED_DUTY_CYCLE
#CONFIG.CLKOUT4_REQUESTED_OUT_FREQ
#CONFIG.CLKOUT4_REQUESTED_PHASE
#CONFIG.CLKOUT4_SEQUENCE_NUMBER
#CONFIG.CLKOUT4_USED
#CONFIG.CLKOUT5_DRIVES
#CONFIG.CLKOUT5_JITTER
#CONFIG.CLKOUT5_MATCHED_ROUTING
#CONFIG.CLKOUT5_PHASE_ERROR
#CONFIG.CLKOUT5_REQUESTED_DUTY_CYCLE
#CONFIG.CLKOUT5_REQUESTED_OUT_FREQ
#CONFIG.CLKOUT5_REQUESTED_PHASE
#CONFIG.CLKOUT5_SEQUENCE_NUMBER
#CONFIG.CLKOUT5_USED
#CONFIG.CLKOUT6_DRIVES
#CONFIG.CLKOUT6_JITTER
#CONFIG.CLKOUT6_MATCHED_ROUTING
#CONFIG.CLKOUT6_PHASE_ERROR
#CONFIG.CLKOUT6_REQUESTED_DUTY_CYCLE
#CONFIG.CLKOUT6_REQUESTED_OUT_FREQ
#CONFIG.CLKOUT6_REQUESTED_PHASE
#CONFIG.CLKOUT6_SEQUENCE_NUMBER
#CONFIG.CLKOUT6_USED
#CONFIG.CLKOUT7_DRIVES
#CONFIG.CLKOUT7_JITTER
#CONFIG.CLKOUT7_MATCHED_ROUTING
#CONFIG.CLKOUT7_PHASE_ERROR
#CONFIG.CLKOUT7_REQUESTED_DUTY_CYCLE
#CONFIG.CLKOUT7_REQUESTED_OUT_FREQ
#CONFIG.CLKOUT7_REQUESTED_PHASE
#CONFIG.CLKOUT7_SEQUENCE_NUMBER
#CONFIG.CLKOUT7_USED
#CONFIG.CLKOUTPHY_REQUESTED_FREQ
#CONFIG.CLK_IN1_BOARD_INTERFACE
#CONFIG.CLK_IN2_BOARD_INTERFACE
#CONFIG.CLK_IN_SEL_PORT
#CONFIG.CLK_OUT1_PORT
#CONFIG.CLK_OUT1_USE_FINE_PS_GUI
#CONFIG.CLK_OUT2_PORT
#CONFIG.CLK_OUT2_USE_FINE_PS_GUI
#CONFIG.CLK_OUT3_PORT
#CONFIG.CLK_OUT3_USE_FINE_PS_GUI
#CONFIG.CLK_OUT4_PORT
#CONFIG.CLK_OUT4_USE_FINE_PS_GUI
#CONFIG.CLK_OUT5_PORT
#CONFIG.CLK_OUT5_USE_FINE_PS_GUI
#CONFIG.CLK_OUT6_PORT
#CONFIG.CLK_OUT6_USE_FINE_PS_GUI
#CONFIG.CLK_OUT7_PORT
#CONFIG.CLK_OUT7_USE_FINE_PS_GUI
#CONFIG.CLK_VALID_PORT
#CONFIG.CLOCK_CLK_IN1.INSERT_VIP
#CONFIG.CLOCK_CLK_OUT1.INSERT_VIP
#CONFIG.CLOCK_MGR_TYPE
#CONFIG.Component_Name
#CONFIG.DADDR_PORT
#CONFIG.DCLK_PORT
#CONFIG.DEN_PORT
#CONFIG.DIFF_CLK_IN1_BOARD_INTERFACE
#CONFIG.DIFF_CLK_IN2_BOARD_INTERFACE
#CONFIG.DIN_PORT
#CONFIG.DOUT_PORT
#CONFIG.DRDY_PORT
#CONFIG.DWE_PORT
#CONFIG.ENABLE_CDDC
#CONFIG.ENABLE_CLKOUTPHY
#CONFIG.ENABLE_CLOCK_MONITOR
#CONFIG.ENABLE_USER_CLOCK0
#CONFIG.ENABLE_USER_CLOCK1
#CONFIG.ENABLE_USER_CLOCK2
#CONFIG.ENABLE_USER_CLOCK3
#CONFIG.Enable_PLL0
#CONFIG.Enable_PLL1
#CONFIG.FEEDBACK_SOURCE
#CONFIG.INPUT_CLK_STOPPED_PORT
#CONFIG.INPUT_MODE
#CONFIG.INTERFACE_SELECTION
#CONFIG.IN_FREQ_UNITS
#CONFIG.IN_JITTER_UNITS
#CONFIG.JITTER_OPTIONS
#CONFIG.JITTER_SEL
#CONFIG.LOCKED_PORT
#CONFIG.MMCM_BANDWIDTH
#CONFIG.MMCM_CLKFBOUT_MULT_F
#CONFIG.MMCM_CLKFBOUT_PHASE
#CONFIG.MMCM_CLKFBOUT_USE_FINE_PS
#CONFIG.MMCM_CLKIN1_PERIOD
#CONFIG.MMCM_CLKIN2_PERIOD
#CONFIG.MMCM_CLKOUT0_DIVIDE_F
#CONFIG.MMCM_CLKOUT0_DUTY_CYCLE
#CONFIG.MMCM_CLKOUT0_PHASE
#CONFIG.MMCM_CLKOUT0_USE_FINE_PS
#CONFIG.MMCM_CLKOUT1_DIVIDE
#CONFIG.MMCM_CLKOUT1_DUTY_CYCLE
#CONFIG.MMCM_CLKOUT1_PHASE
#CONFIG.MMCM_CLKOUT1_USE_FINE_PS
#CONFIG.MMCM_CLKOUT2_DIVIDE
#CONFIG.MMCM_CLKOUT2_DUTY_CYCLE
#CONFIG.MMCM_CLKOUT2_PHASE
#CONFIG.MMCM_CLKOUT2_USE_FINE_PS
#CONFIG.MMCM_CLKOUT3_DIVIDE
#CONFIG.MMCM_CLKOUT3_DUTY_CYCLE
#CONFIG.MMCM_CLKOUT3_PHASE
#CONFIG.MMCM_CLKOUT3_USE_FINE_PS
#CONFIG.MMCM_CLKOUT4_CASCADE
#CONFIG.MMCM_CLKOUT4_DIVIDE
#CONFIG.MMCM_CLKOUT4_DUTY_CYCLE
#CONFIG.MMCM_CLKOUT4_PHASE
#CONFIG.MMCM_CLKOUT4_USE_FINE_PS
#CONFIG.MMCM_CLKOUT5_DIVIDE
#CONFIG.MMCM_CLKOUT5_DUTY_CYCLE
#CONFIG.MMCM_CLKOUT5_PHASE
#CONFIG.MMCM_CLKOUT5_USE_FINE_PS
#CONFIG.MMCM_CLKOUT6_DIVIDE
#CONFIG.MMCM_CLKOUT6_DUTY_CYCLE
#CONFIG.MMCM_CLKOUT6_PHASE
#CONFIG.MMCM_CLKOUT6_USE_FINE_PS
#CONFIG.MMCM_CLOCK_HOLD
#CONFIG.MMCM_COMPENSATION
#CONFIG.MMCM_DIVCLK_DIVIDE
#CONFIG.MMCM_NOTES
#CONFIG.MMCM_REF_JITTER1
#CONFIG.MMCM_REF_JITTER2
#CONFIG.MMCM_STARTUP_WAIT
#CONFIG.NUM_OUT_CLKS
#CONFIG.OPTIMIZE_CLOCKING_STRUCTURE_EN
#CONFIG.OVERRIDE_MMCM
#CONFIG.OVERRIDE_PLL
#CONFIG.PHASESHIFT_MODE
#CONFIG.PHASE_DUTY_CONFIG
#CONFIG.PLATFORM
#CONFIG.PLL_BANDWIDTH
#CONFIG.PLL_CLKFBOUT_MULT
#CONFIG.PLL_CLKFBOUT_PHASE
#CONFIG.PLL_CLKIN_PERIOD
#CONFIG.PLL_CLKOUT0_DIVIDE
#CONFIG.PLL_CLKOUT0_DUTY_CYCLE
#CONFIG.PLL_CLKOUT0_PHASE
#CONFIG.PLL_CLKOUT1_DIVIDE
#CONFIG.PLL_CLKOUT1_DUTY_CYCLE
#CONFIG.PLL_CLKOUT1_PHASE
#CONFIG.PLL_CLKOUT2_DIVIDE
#CONFIG.PLL_CLKOUT2_DUTY_CYCLE
#CONFIG.PLL_CLKOUT2_PHASE
#CONFIG.PLL_CLKOUT3_DIVIDE
#CONFIG.PLL_CLKOUT3_DUTY_CYCLE
#CONFIG.PLL_CLKOUT3_PHASE
#CONFIG.PLL_CLKOUT4_DIVIDE
#CONFIG.PLL_CLKOUT4_DUTY_CYCLE
#CONFIG.PLL_CLKOUT4_PHASE
#CONFIG.PLL_CLKOUT5_DIVIDE
#CONFIG.PLL_CLKOUT5_DUTY_CYCLE
#CONFIG.PLL_CLKOUT5_PHASE
#CONFIG.PLL_CLK_FEEDBACK
#CONFIG.PLL_COMPENSATION
#CONFIG.PLL_DIVCLK_DIVIDE
#CONFIG.PLL_NOTES
#CONFIG.PLL_REF_JITTER
#CONFIG.POWER_DOWN_PORT
#CONFIG.PRECISION
#CONFIG.PRIMARY_PORT
#CONFIG.PRIMITIVE
#CONFIG.PRIMTYPE_SEL
#CONFIG.PRIM_IN_FREQ
#CONFIG.PRIM_IN_JITTER
#CONFIG.PRIM_IN_TIMEPERIOD
#CONFIG.PRIM_SOURCE
#CONFIG.PSCLK_PORT
#CONFIG.PSDONE_PORT
#CONFIG.PSEN_PORT
#CONFIG.PSINCDEC_PORT
#CONFIG.REF_CLK.INSERT_VIP
#CONFIG.REF_CLK_FREQ
#CONFIG.RELATIVE_INCLK
#CONFIG.RESET.INSERT_VIP
#CONFIG.RESETN.INSERT_VIP
#CONFIG.RESET_BOARD_INTERFACE
#CONFIG.RESET_PORT
#CONFIG.RESET_TYPE
#CONFIG.SECONDARY_IN_FREQ
#CONFIG.SECONDARY_IN_JITTER
#CONFIG.SECONDARY_IN_TIMEPERIOD
#CONFIG.SECONDARY_PORT
#CONFIG.SECONDARY_SOURCE
#CONFIG.SS_MODE
#CONFIG.SS_MOD_FREQ
#CONFIG.SS_MOD_TIME
#CONFIG.STATUS_PORT
#CONFIG.SUMMARY_STRINGS
#CONFIG.S_AXI_ACLK.INSERT_VIP
#CONFIG.S_AXI_LITE.INSERT_VIP
#CONFIG.S_AXI_RESETN.INSERT_VIP
#CONFIG.USER_CLK_FREQ0
#CONFIG.USER_CLK_FREQ1
#CONFIG.USER_CLK_FREQ2
#CONFIG.USER_CLK_FREQ3
#CONFIG.USE_BOARD_FLOW
#CONFIG.USE_CLKFB_STOPPED
#CONFIG.USE_CLK_VALID
#CONFIG.USE_CLOCK_SEQUENCING
#CONFIG.USE_DYN_PHASE_SHIFT
#CONFIG.USE_DYN_RECONFIG
#CONFIG.USE_FREEZE
#CONFIG.USE_FREQ_SYNTH
#CONFIG.USE_INCLK_STOPPED
#CONFIG.USE_INCLK_SWITCHOVER
#CONFIG.USE_LOCKED
#CONFIG.USE_MAX_I_JITTER
#CONFIG.USE_MIN_O_JITTER
#CONFIG.USE_MIN_POWER
#CONFIG.USE_PHASE_ALIGNMENT
#CONFIG.USE_POWER_DOWN
#CONFIG.USE_RESET
#CONFIG.USE_SAFE_CLOCK_STARTUP
#CONFIG.USE_SPREAD_SPECTRUM
#CONFIG.USE_STATUS
#CORE_REVISION
#CUSTOMIZATION_CRC
#DCP_RESOURCE_DATA
#DEFINITION_SOURCE
#DELIVERED_TARGETS
#DESIGN_TOOL_CONTEXTS
#FAMILY
#INTERNAL_MEMORY_ADDRESS
#IPDEF
#IP_CORE_CONTAINER
#IP_DIR
#IP_FILE
#IP_OUTPUT_DIR
#IP_SHARED_DIR
#IS_BD_CONTEXT
#IS_BOARD_AWARE
#IS_IP_GENERATED
#IS_LOCKED
#KNOWN_TARGETS
#LOCK_DETAILS
#NAME
#PART
#REQUIRES_VIP
#SCOPE
#SELECTED_SIM_MODEL
#STALE_TARGETS
#SUPPORTED_TARGETS
#SUPPORTS_MODREF
#SW_VERSION
#UNSUPPORTED_SIMULATORS
#UPGRADE_RESULT
#UPGRADE_VERSIONS
#USED_LICENSE_KEYS
#USER_LOCKED
#USE_IP_SHARED_DIR
#XPM_LIBRARIES

# create a ppl 
create_ip -name clk_wiz -vendor xilinx.com -library ip -version 6.0 -module_name clk_wiz_ppl_0

set_property -dict [list \
  CONFIG.CLKOUT1_DRIVES {Buffer} \
  CONFIG.CLKOUT1_JITTER {167.017} \
  CONFIG.CLKOUT1_PHASE_ERROR {114.212} \
  CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {50.000} \
  CONFIG.CLKOUT2_DRIVES {Buffer} \
  CONFIG.CLKOUT3_DRIVES {Buffer} \
  CONFIG.CLKOUT4_DRIVES {Buffer} \
  CONFIG.CLKOUT5_DRIVES {Buffer} \
  CONFIG.CLKOUT6_DRIVES {Buffer} \
  CONFIG.CLKOUT7_DRIVES {Buffer} \
  CONFIG.CLK_OUT1_PORT {clock_out} \
  CONFIG.MMCM_BANDWIDTH {OPTIMIZED} \
  CONFIG.MMCM_CLKFBOUT_MULT_F {8} \
  CONFIG.MMCM_CLKOUT0_DIVIDE_F {16} \
  CONFIG.MMCM_COMPENSATION {AUTO} \
  CONFIG.PRIMARY_PORT {clock_in} \
  CONFIG.PRIMITIVE {PLL} \
] [get_ips clk_wiz_ppl_0]



